[package]
name = "thecurse_game"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["dev"]
dev = ["thecurse_core/dev", "dep:bevy-inspector-egui"]

[dependencies]
thecurse_core.workspace = true

bevy.workspace = true
bevy-inspector-egui = { workspace = true, optional = true }
bevy_console.workspace = true

thiserror.workspace = true
rand.workspace = true
clap.workspace = true

serde.workspace = true
ron.workspace = true
smol.workspace = true
futures.workspace = true

[lints]
workspace = true
