[workspace]
members = ["core", "game", "editor", "server"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["faervan <faervan@proton.me>"]

[workspace.dependencies]
thecurse_core.path = "core"
mini_udp.path = "../mini_udp/mini_udp"

# Bevy & plugins
bevy = { version = "0.18", default-features = false, features = [
  "3d",
  "serialize",
] }
avian3d = { version = "0.5", default-features = false, features = [
  # Default
  "3d",
  "f32",
  "parry-f32",
  "collider-from-mesh",
  "bevy_scene",
  "bevy_picking",
  "debug-plugin",
  "parallel",
  # Non-default
  "simd",
  "serialize",
] }
bevy_skein.version = "0.5"
vleue_navigator = { version = "0.15", default-features = false, features = [
  "avian3d",
  "detailed-layers",
] }
bevy_console = "0.17"

# Dev dependencies
egui = "0.33"
egui_dock = "0.18"
bevy_egui.version = "0.39"
bevy-inspector-egui.version = "0.36"

# Logging
# Set max log levels. This helps avoid unwanted low-severity log spam, which can affect performance.
log = { version = "0.4", features = [
  "max_level_debug",
  "release_max_level_warn",
] }
tracing = { version = "0.1", features = [
  "max_level_debug",
  "release_max_level_warn",
] }

# Networking
serde = { version = "1", features = ["derive"] }
ron = "0.12"
postcard = { version = "1.1", features = ["experimental-derive", "alloc"] }
crc = "3.4"
smol = "2.0"
event-listener = "5.4"
futures = "0.3"

# Useful rust utilities
thiserror = "2"
bitflags = "2.10"
rand = "0.10"
ambassador = "0.5"
clap = { version = "4.5", features = ["derive"] }

[workspace.lints.rust]
# Mark `bevy_lint` as a valid `cfg`, as it is set when the Bevy linter runs.
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(bevy_lint)"] }

[workspace.lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
# Make sure macros use their standard braces, such as `[]` for `bevy_ecs::children!`.
nonstandard_macro_braces = "warn"

[profile.dev]
codegen-units = 512

# Dependency optimization
[profile.dev.package."*"]
opt-level = 3

# Release optimization
[profile.release]
lto = "fat"
panic = "abort"
