[package]
name = "dreamgame_core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = []

dev = [
  "bevy/dynamic_linking",
  "bevy/dev",
  "bevy/track_location",
  # Enables hot reload for in-memory asset providers
  "bevy/embedded_watcher",
]

[dependencies]
mini_udp.workspace = true

bevy.workspace = true
avian3d.workspace = true
vleue_navigator.workspace = true

serde.workspace = true
postcard.workspace = true
smol.workspace = true
futures.workspace = true

thiserror.workspace = true
bitflags.workspace = true
rand.workspace = true
ambassador.workspace = true
clap.workspace = true

[lints]
workspace = true
