[package]
name = "thecurse_core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["game"]

dev = [
  "bevy/dynamic_linking",
  "bevy/dev",
  "bevy/track_location",
  "bevy/file_watcher",
  # Enables hot reload for in-memory asset providers
  "bevy/embedded_watcher",
  # Needed for https://github.com/Lommix/bevy_inspector.nvim
  "bevy/bevy_remote",
]
game = []

[dependencies]
mini_udp.workspace = true

bevy.workspace = true
avian3d.workspace = true
vleue_navigator.workspace = true

thiserror.workspace = true
bitflags.workspace = true
rand.workspace = true
ambassador.workspace = true

serde.workspace = true
ron.workspace = true
postcard.workspace = true
smol.workspace = true
futures.workspace = true

[lints]
workspace = true
