[package]
name = "dreamgame_server"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["dev"]
dev = ["dreamgame_core/dev"]

[dependencies]
dreamgame_core.workspace = true

bevy.workspace = true

postcard.workspace = true
smol.workspace = true
event-listener.workspace = true
futures.workspace = true

rand.workspace = true
clap.workspace = true

[lints]
workspace = true
